// Code generated by tools/gen_kpm_profiles.py; DO NOT EDIT.

package kpm

type ProductProfile struct {
	Manufacturer   string
	Model          string
	Device         string
	Fingerprint    string
	AndroidRelease string
	SDK            uint32
	SecurityPatch  string
}

type KernelProfile struct {
	Release             string
	BuildID             string
	ACKCommit           string
	BTFSHA256           string
	PageSize            uint32
	VABits              uint32
	TaskStructSize      uint32
	CredSize            uint32
	PerfEventSize       uint32
	TaskCommLen         uint32
	LinuxBannerCapacity uint32
}

type KPatchProfile struct {
	Kpver                   string
	Kver                    string
	SDKVersion              string
	SDKCommit               string
	ControlPath             string
	ModuleName              string
	SafeUnloadSymbol        string
	MemcpyKFunc             string
	MemsetKFunc             string
	KFuncExportsArePointers bool
}

type TaskOffsets struct {
	ThreadInfoFlags  uint32
	CPU              uint32
	State            uint32
	Usage            uint32
	Tasks            uint32
	MM               uint32
	ActiveMM         uint32
	ExitState        uint32
	PID              uint32
	TGID             uint32
	RealParent       uint32
	Parent           uint32
	ThreadPID        uint32
	PIDLinks         uint32
	ThreadNode       uint32
	StartTime        uint32
	StartBoottime    uint32
	RealCred         uint32
	Cred             uint32
	Comm             uint32
	Signal           uint32
	PerfEventCtxp    uint32
	PerfEventList    uint32
	Thread           uint32
	SignalThreadHead uint32
}

type CredOffsets struct {
	UID uint32
}

type PerfEventOffsets struct {
	State       uint32
	Attr        uint32
	AttrBPType  uint32
	AttrBPAddr  uint32
	AttrBPLen   uint32
	HW          uint32
	ArchAddress uint32
	ArchTrigger uint32
	ArchCtrl    uint32
	HWTarget    uint32
	Ctx         uint32
	OnCPU       uint32
	CPU         uint32
	Owner       uint32
	ContextTask uint32
}

type DebugProfile struct {
	DFR0      uint64
	DebugArch uint32
	BRPs      uint32
	WRPs      uint32
	CtxCmps   uint32
	MaxCPUs   uint32
}

type KernelLayouts struct {
	WorkStructSize      uint32
	WorkData            uint32
	WorkEntry           uint32
	WorkFunc            uint32
	WorkDataInit        uint64
	PtRegsSize          uint32
	PtRegsRegs          uint32
	PtRegsSp            uint32
	PtRegsPc            uint32
	PtRegsPstate        uint32
	PerCPUPointerStride uint32
}

type MapsProfile struct {
	MaxSnapshotBytes    uint32
	MaxChunkBytes       uint32
	SeqFileSize         uint32
	SeqBuf              uint32
	SeqSize             uint32
	SeqFrom             uint32
	SeqCount            uint32
	SeqPadUntil         uint32
	SeqPrivate          uint32
	ProcMapsPrivateSize uint32
	ProcTask            uint32
	ProcMM              uint32
	ProcIter            uint32
	VMAIteratorSize     uint32
	MasTree             uint32
	MasIndex            uint32
	MasLast             uint32
	MasNode             uint32
	MasStatus           uint32
	MMStructSize        uint32
	MMMapleTree         uint32
	VMAStructSize       uint32
	VMAStart            uint32
	VMAEnd              uint32
	MasStartNode        uint64
	MaStartStatus       uint32
	ShowMapVMAArgs      uint32
}

type KernelSymbols struct {
	LinuxBanner             string
	InitTask                string
	FinishTaskSwitch        string
	DoExit                  string
	BreakpointHandler       string
	WatchpointHandler       string
	SingleStepHandler       string
	BPOnReg                 string
	WpOnReg                 string
	PerCPUOffset            string
	NrCPUIDs                string
	SystemUnboundWq         string
	QueueWorkOn             string
	FlushWork               string
	SynchronizeRCUTasks     string
	ScheduleOnEachCPU       string
	KtimeGetMonoFastNs      string
	CopyFromKernelNofault   string
	ShowMapVMA              string
	FindVMA                 string
	MasWalk                 string
	GetTaskMM               string
	Mmput                   string
	MmapReadLockKillable    string
	MmapReadUnlock          string
	RustHelperGetTaskStruct string
	RustHelperPutTaskStruct string
	VmallocNoprof           string
	Vfree                   string
}

type HookABI struct {
	FinishTaskSwitchArgs  uint32
	DoExitArgs            uint32
	BreakpointHandlerArgs uint32
	WatchpointHandlerArgs uint32
	SingleStepHandlerArgs uint32
}

type ProfileQuirks struct {
	ControlUnderRCU         bool
	UnloadRequiresQuiescent bool
	CPUHotplugWhileArmed    bool
	SafeUnloadRequired      bool
	LinuxBannerPrefixOK     bool
}

type DeviceProfile struct {
	ID        string
	Product   ProductProfile
	Kernel    KernelProfile
	KPatch    KPatchProfile
	Task      TaskOffsets
	Cred      CredOffsets
	PerfEvent PerfEventOffsets
	Debug     DebugProfile
	Layout    KernelLayouts
	Maps      MapsProfile
	Symbols   KernelSymbols
	Hooks     HookABI
	Quirks    ProfileQuirks
}

var DeviceProfiles = []DeviceProfile{
	{
		ID: "oneplus-plk110-a16-b4999618-d05",
		Product: ProductProfile{
			Manufacturer:   "OnePlus",
			Model:          "PLK110",
			Device:         "OP60FFL1",
			Fingerprint:    "OnePlus/PLK110/OP60FFL1:16/BP2A.250605.015/B.4999618-258d62aa-25a17fd:user/release-keys",
			AndroidRelease: "16",
			SDK:            36,
			SecurityPatch:  "2026-06-01",
		},
		Kernel: KernelProfile{
			Release:             "6.12.23-android16-5-gb2a876903b49-ab14541642-4k",
			BuildID:             "30b974f296b5639f597e345adb578a0cbcabeb03",
			ACKCommit:           "b2a876903b495c444a94b16f50d1463ffe953957",
			BTFSHA256:           "75b509d7abaed46f57cf26c3780122b5abfae889cde4a22edf1812bba3ce3320",
			PageSize:            4096,
			VABits:              39,
			TaskStructSize:      5184,
			CredSize:            184,
			PerfEventSize:       1120,
			TaskCommLen:         16,
			LinuxBannerCapacity: 256,
		},
		KPatch: KPatchProfile{
			Kpver:                   "d05",
			Kver:                    "60c17",
			SDKVersion:              "0.13.5-2",
			SDKCommit:               "0fe6d142266b80e5aa445a7ea1534f88a8f33a35",
			ControlPath:             "/data/adb/modules/KPatch-Next/bin/kpatch",
			ModuleName:              "stackplz-kpm",
			SafeUnloadSymbol:        "kpm_safe_unload_v1",
			MemcpyKFunc:             "kf_memcpy",
			MemsetKFunc:             "kf_memset",
			KFuncExportsArePointers: true,
		},
		Task: TaskOffsets{
			ThreadInfoFlags:  0,
			CPU:              40,
			State:            48,
			Usage:            64,
			Tasks:            1592,
			MM:               1672,
			ActiveMM:         1680,
			ExitState:        1696,
			PID:              1800,
			TGID:             1804,
			RealParent:       1816,
			Parent:           1824,
			ThreadPID:        1904,
			PIDLinks:         1912,
			ThreadNode:       1976,
			StartTime:        2104,
			StartBoottime:    2112,
			RealCred:         2296,
			Cred:             2304,
			Comm:             2320,
			Signal:           2392,
			PerfEventCtxp:    2992,
			PerfEventList:    3048,
			Thread:           3488,
			SignalThreadHead: 16,
		},
		Cred: CredOffsets{
			UID: 8,
		},
		PerfEvent: PerfEventOffsets{
			State:       168,
			Attr:        216,
			AttrBPType:  268,
			AttrBPAddr:  272,
			AttrBPLen:   280,
			HW:          360,
			ArchAddress: 360,
			ArchTrigger: 368,
			ArchCtrl:    376,
			HWTarget:    456,
			Ctx:         552,
			OnCPU:       664,
			CPU:         668,
			Owner:       688,
			ContextTask: 152,
		},
		Debug: DebugProfile{
			DFR0:      19722761426713,
			DebugArch: 9,
			BRPs:      6,
			WRPs:      4,
			CtxCmps:   2,
			MaxCPUs:   8,
		},
		Layout: KernelLayouts{
			WorkStructSize:      32,
			WorkData:            0,
			WorkEntry:           8,
			WorkFunc:            24,
			WorkDataInit:        4503599625273344,
			PtRegsSize:          336,
			PtRegsRegs:          0,
			PtRegsSp:            248,
			PtRegsPc:            256,
			PtRegsPstate:        264,
			PerCPUPointerStride: 8,
		},
		Maps: MapsProfile{
			MaxSnapshotBytes:    2097152,
			MaxChunkBytes:       1536,
			SeqFileSize:         136,
			SeqBuf:              0,
			SeqSize:             8,
			SeqFrom:             16,
			SeqCount:            24,
			SeqPadUntil:         32,
			SeqPrivate:          128,
			ProcMapsPrivateSize: 120,
			ProcTask:            8,
			ProcMM:              16,
			ProcIter:            24,
			VMAIteratorSize:     72,
			MasTree:             0,
			MasIndex:            8,
			MasLast:             16,
			MasNode:             24,
			MasStatus:           56,
			MMStructSize:        1216,
			MMMapleTree:         64,
			VMAStructSize:       256,
			VMAStart:            0,
			VMAEnd:              8,
			MasStartNode:        1,
			MaStartStatus:       1,
			ShowMapVMAArgs:      2,
		},
		Symbols: KernelSymbols{
			LinuxBanner:             "linux_banner",
			InitTask:                "init_task",
			FinishTaskSwitch:        "finish_task_switch",
			DoExit:                  "do_exit",
			BreakpointHandler:       "breakpoint_handler",
			WatchpointHandler:       "watchpoint_handler",
			SingleStepHandler:       "single_step_handler",
			BPOnReg:                 "bp_on_reg",
			WpOnReg:                 "wp_on_reg",
			PerCPUOffset:            "__per_cpu_offset",
			NrCPUIDs:                "nr_cpu_ids",
			SystemUnboundWq:         "system_unbound_wq",
			QueueWorkOn:             "queue_work_on",
			FlushWork:               "flush_work",
			SynchronizeRCUTasks:     "synchronize_rcu_tasks",
			ScheduleOnEachCPU:       "schedule_on_each_cpu",
			KtimeGetMonoFastNs:      "ktime_get_mono_fast_ns",
			CopyFromKernelNofault:   "copy_from_kernel_nofault",
			ShowMapVMA:              "show_map_vma",
			FindVMA:                 "find_vma",
			MasWalk:                 "mas_walk",
			GetTaskMM:               "get_task_mm",
			Mmput:                   "mmput",
			MmapReadLockKillable:    "mmap_read_lock_killable",
			MmapReadUnlock:          "mmap_read_unlock",
			RustHelperGetTaskStruct: "rust_helper_get_task_struct",
			RustHelperPutTaskStruct: "rust_helper_put_task_struct",
			VmallocNoprof:           "vmalloc_noprof",
			Vfree:                   "vfree",
		},
		Hooks: HookABI{
			FinishTaskSwitchArgs:  1,
			DoExitArgs:            1,
			BreakpointHandlerArgs: 3,
			WatchpointHandlerArgs: 3,
			SingleStepHandlerArgs: 3,
		},
		Quirks: ProfileQuirks{
			ControlUnderRCU:         true,
			UnloadRequiresQuiescent: true,
			CPUHotplugWhileArmed:    false,
			SafeUnloadRequired:      false,
			LinuxBannerPrefixOK:     true,
		},
	},
}

func FindDeviceProfile(id string) (DeviceProfile, bool) {
	for _, profile := range DeviceProfiles {
		if profile.ID == id {
			return profile, true
		}
	}
	return DeviceProfile{}, false
}

const DefaultProfileID = "oneplus-plk110-a16-b4999618-d05"

func DefaultDeviceProfile() DeviceProfile {
	profile, found := FindDeviceProfile(DefaultProfileID)
	if !found {
		panic("missing default device profile " + DefaultProfileID)
	}
	return profile
}
